# Generated by Django 4.2.5 on 2023-12-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classbasedviewsapp5', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
