# Generated by Django 4.2.5 on 2023-12-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelinheritanceapp', '0002_bank_bankmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('ulocation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
            ],
            options={
                'ordering': ['ulocation'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('modelinheritanceapp.university',),
        ),
    ]
